import { ChevronLeftIcon } from "@heroicons/react/20/solid";
import { useMemo, useState, useEffect } from "react";
import { Country, State, City } from "country-state-city";
import {
  Controller,
  useForm,
  type FieldPath,
} from "react-hook-form";
import { Link, useNavigate } from "react-router";

import { Page } from "@/components/shared/Page";
import { Stepper } from "@/components/shared/Stepper";
import { DatePicker } from "@/components/shared/form/Datepicker";
import { Combobox } from "@/components/shared/form/StyledCombobox";
import { Button, Card, Input, Switch } from "@/components/ui";
import { Post, toasterrormsg, toastsuccessmsg, Get } from "@/ApiHelper";

import { PaperClipIcon } from "@heroicons/react/24/solid";
import { genderOptions } from "../../../../master/shared/constants";
import { buildFormData } from "../../../../master/shared/toFormData";

const STEP_LABELS = [
  "Personal Details",
  "Identity & KYC",
  "Address Details",
  "Employee Details",
  "Work Information",
];

// ---------------- Local option lists ----------------
const maritalStatusOptions = [
  { id: "single", label: "Single" },
  { id: "married", label: "Married" },
  { id: "divorced", label: "Divorced" },
  { id: "widowed", label: "Widowed" },
];

const bloodGroupOptions = [
  { id: "A+", label: "A+" },
  { id: "A-", label: "A-" },
  { id: "B+", label: "B+" },
  { id: "B-", label: "B-" },
  { id: "AB+", label: "AB+" },
  { id: "AB-", label: "AB-" },
  { id: "O+", label: "O+" },
  { id: "O-", label: "O-" },
];

const employeeTypeOptions = [
  { id: "permanent", label: "Permanent" },
  { id: "probation", label: "Probation" },
  { id: "trainee", label: "Trainee" },
  { id: "contract", label: "Contract" },
  { id: "intern", label: "Intern" },
];

const employeeStatusOptions = [
  { id: "active", label: "Active" },
  { id: "on_notice", label: "On Notice" },
  { id: "suspended", label: "Suspended" },
  { id: "resigned", label: "Resigned" },
  { id: "terminated", label: "Terminated" },
  { id: "retired", label: "Retired" },
];

// ---------------- Work Information option lists ----------------
const daysOfWeekOptions = [
  { id: "monday", label: "Monday" },
  { id: "tuesday", label: "Tuesday" },
  { id: "wednesday", label: "Wednesday" },
  { id: "thursday", label: "Thursday" },
  { id: "friday", label: "Friday" },
  { id: "saturday", label: "Saturday" },
  { id: "sunday", label: "Sunday" },
];

const workingShiftOptions = [
  { id: "general", label: "General Shift" },
  { id: "morning", label: "Morning Shift" },
  { id: "evening", label: "Evening Shift" },
  { id: "night", label: "Night Shift" },
];

// ---------------- Local data shape ----------------
export interface EmployeeEntry {
  id: string;
  employeeId: string; // display-only "EMP-XXXXXX" code, generated by backend
  financialYearId: string;
  // Personal Details
  firstName: string;
  lastName: string;
  middleName?: string;
  dateOfBirth: string;
  gender: string;
  maritalStatus: string;
  bloodGroup: string;
  personalMobileNo: string;
  personalEmail: string;

  // Identity & KYC
  aadharNumber?: string;
  aadharCardUpload?: File | string | null;
  drivingLicenceNumber?: string;
  drivingLicenceUpload?: File | string | null;
  panNumber?: string;
  panUpload?: File | string | null;
  voterIdNumber?: string;
  voterIdUpload?: File | string | null;

  // Address Details — Current
  address: string;
  country: string;
  state: string;
  city: string;
  pincode: string;

  // Address Details — Permanent
  sameAsPermanentAddress: boolean;
  permanentAddress?: string;
  permanentCountry?: string;
  permanentState?: string;
  permanentCity?: string;
  permanentPincode?: string;

  // Employee Details
  joiningDate: string;
  employeeType: string;
  designation: string;
  branchLocation: string;
  employeeStatus: string;
  noticePeriod: string;

  // Work Information
  workingDays: string[];
  weeklyOff: string;
  workingHoursFrom: string;
  workingHoursTo: string;
  workingShift: string;
}

const emptyEmployee = (): EmployeeEntry => ({
  id: "",
  employeeId: "",
  financialYearId: "",
  firstName: "",
  lastName: "",
  middleName: "",
  dateOfBirth: "",
  gender: "",
  maritalStatus: "",
  bloodGroup: "",
  personalMobileNo: "",
  personalEmail: "",
  aadharNumber: "",
  aadharCardUpload: null,
  drivingLicenceNumber: "",
  drivingLicenceUpload: null,
  panNumber: "",
  panUpload: null,
  voterIdNumber: "",
  voterIdUpload: null,
  address: "",
  country: "",
  state: "",
  city: "",
  pincode: "",
  sameAsPermanentAddress: true,
  permanentAddress: "",
  permanentCountry: "",
  permanentState: "",
  permanentCity: "",
  permanentPincode: "",
  joiningDate: "",
  employeeType: "",
  designation: "",
  branchLocation: "",
  employeeStatus: "",
  noticePeriod: "",
  workingDays: [],
  weeklyOff: "",
  workingHoursFrom: "",
  workingHoursTo: "",
  workingShift: "",
});

const STEP1_REQUIRED_FIELDS = [
  "firstName",
  "lastName",
  "dateOfBirth",
  "gender",
  "maritalStatus",
  "personalMobileNo",
] as const;

const STEP3_REQUIRED_FIELDS = [
  "address",
  "country",
  "state",
  "city",
  "pincode",
] as const;

const STEP4_REQUIRED_FIELDS = [
  "joiningDate",
  "employeeType",
  "designation",
  "employeeStatus",
] as const;

const STEP5_REQUIRED_FIELDS = [
  "workingDays",
  "weeklyOff",
  "workingHoursFrom",
  "workingHoursTo",
  "workingShift",
] as const;

interface EmployeeOption {
  id: string;
  employeeName: string;
  mobileNumber?: string;
  email?: string;
  department?: string;
  branch?: string;
  label: string;
}

// Number field key <-> its upload field key <-> display label
const KYC_FIELDS: Array<{
  numberField:
    | "aadharNumber"
    | "drivingLicenceNumber"
    | "panNumber"
    | "voterIdNumber";
  uploadField:
    | "aadharCardUpload"
    | "drivingLicenceUpload"
    | "panUpload"
    | "voterIdUpload";
  label: string;
}> = [
  {
    numberField: "aadharNumber",
    uploadField: "aadharCardUpload",
    label: "Aadhar Card",
  },
  {
    numberField: "drivingLicenceNumber",
    uploadField: "drivingLicenceUpload",
    label: "Driving Licence",
  },
  { numberField: "panNumber", uploadField: "panUpload", label: "PAN Card" },
  {
    numberField: "voterIdNumber",
    uploadField: "voterIdUpload",
    label: "Voter ID",
  },
];

export default function EmployeeRegisterWizard() {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [submitting, setSubmitting] = useState(false);

  const {
    register,
    control,
    trigger,
    getValues,
    setValue,
    watch,
    formState: { errors },
  } = useForm<EmployeeEntry>({
    defaultValues: emptyEmployee(),
  });

  const [employeeOptions, setEmployeeOptions] = useState<EmployeeOption[]>([]);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption[]>(
    [],
  );
  const [selectEmployeeError, setSelectEmployeeError] = useState("");
  const [kycErrors, setKycErrors] = useState<Record<string, string>>({});

  // ---- Fetch next display Employee ID (EMP-000123) from backend ----
  useEffect(() => {
    const fetchNextEmployeeId = async () => {
      try {
        const financialYearId = localStorage.getItem("financialYearId");



        if (!financialYearId) {
          toasterrormsg(
            "Financial Year not found. Please select a company year.",
          );
          return;
        }

        // IMPORTANT:
        // Store financialYearId inside react-hook-form
        setValue("financialYearId", financialYearId);

        const response = await Get(
          "hr/employee/next-employee-id",
          { financialYearId },
          false,
        );



        if (response?.data?.success || response?.data?.status === 200) {
          setValue("employeeId", response.data.data.employeeId);
        } else {
          toasterrormsg(
            response?.data?.message ||
              "Failed to generate Employee ID. Please retry.",
          );
        }
      } catch (error) {
        console.error("Employee ID generation error:", error);
        toasterrormsg("Failed to generate Employee ID. Please retry.");
      }
    };

    fetchNextEmployeeId();
  }, [setValue]);

  // ---- Fetch employees that are created (master) but not yet registered (wizard) ----
  useEffect(() => {
    const fetchEmployees = async () => {
      try {
        const response = await Get("hr/employee/unregistered-list", {}, false);
        if (response?.data?.success || response?.data?.status === 200) {
          const list = response.data.data || [];
          setEmployeeOptions(
            list.map((item: any) => ({
              id: String(item.employeeId),
              employeeName: item.employeeName,
              mobileNumber: item.mobileNumber || "",
              email: item.email || "",
              department: item.department || "",
              branch: item.branch || "",
              label: `${item.employeeName} - ${item.mobileNumber || ""}`,
            })),
          );
        }
      } catch (error) {
        console.error("Employee list error:", error);
      }
    };

    fetchEmployees();
  }, []);

  // ---- Auto-fill Personal Details when an employee is picked ----
  useEffect(() => {
    const emp = selectedEmployee?.[0];
    if (!emp) return;

    setSelectEmployeeError("");

    const [first, ...rest] = (emp.employeeName || "").trim().split(" ");
    setValue("firstName", first || "");
    setValue("lastName", rest.join(" ") || "");
    setValue("personalMobileNo", emp.mobileNumber || "");
    setValue("personalEmail", emp.email || "");
  }, [selectedEmployee]);

  const sameAsPermanentAddress = watch("sameAsPermanentAddress");

  // ===== Current address country/state/city cascading dropdowns =====
  const [currentCountryCode, setCurrentCountryCode] = useState("");
  const [currentStateCode, setCurrentStateCode] = useState("");

  // ===== Permanent address country/state/city cascading dropdowns =====
  const [permanentCountryCode, setPermanentCountryCode] = useState("");
  const [permanentStateCode, setPermanentStateCode] = useState("");

  const countryOptions = useMemo(
    () =>
      Country.getAllCountries().map((c) => ({ id: c.isoCode, label: c.name })),
    [],
  );

  const currentStateOptions = useMemo(() => {
    if (!currentCountryCode) return [];
    return State.getStatesOfCountry(currentCountryCode).map((s) => ({
      id: s.isoCode,
      label: s.name,
    }));
  }, [currentCountryCode]);

  const currentCityOptions = useMemo(() => {
    if (!currentCountryCode || !currentStateCode) return [];
    return City.getCitiesOfState(currentCountryCode, currentStateCode).map(
      (c) => ({
        id: c.name,
        label: c.name,
      }),
    );
  }, [currentCountryCode, currentStateCode]);

  const permanentStateOptions = useMemo(() => {
    if (!permanentCountryCode) return [];
    return State.getStatesOfCountry(permanentCountryCode).map((s) => ({
      id: s.isoCode,
      label: s.name,
    }));
  }, [permanentCountryCode]);

  const permanentCityOptions = useMemo(() => {
    if (!permanentCountryCode || !permanentStateCode) return [];
    return City.getCitiesOfState(permanentCountryCode, permanentStateCode).map(
      (c) => ({
        id: c.name,
        label: c.name,
      }),
    );
  }, [permanentCountryCode, permanentStateCode]);

 const goNext = async (
  fields: readonly FieldPath<EmployeeEntry>[],
  nextStep: number,
) => {
  const valid = await trigger(fields);

  if (!valid) return;

  setStep(nextStep);
};

  // ---- Step 2: KYC bidirectional validation — number <-> image, both ways ----
  const validateKycStep = () => {
    const values = getValues();
    const nextErrors: Record<string, string> = {};

    KYC_FIELDS.forEach(({ numberField, uploadField, label }) => {
      const number = (values[numberField] || "").toString().trim();
      const file = values[uploadField];

      if (number && !file) {
        nextErrors[uploadField] = `Upload ${label} image`;
      }
      if (!number && file) {
        nextErrors[numberField] = `Enter ${label} number`;
      }
    });

    setKycErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  const renderKycField = (
    numberField:
      | "aadharNumber"
      | "drivingLicenceNumber"
      | "panNumber"
      | "voterIdNumber",
    uploadField:
      | "aadharCardUpload"
      | "drivingLicenceUpload"
      | "panUpload"
      | "voterIdUpload",
    label: string,
  ) => (
    <div>
      <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-200">
        {label}
      </label>

      <Controller
        control={control}
        name={uploadField}
        render={({ field: { value, onChange } }) => (
          <>
            <div className="flex items-stretch">
              <div className="w-[68%]">
                <input
                  type="text"
                  placeholder={`Enter ${label}`}
                  {...register(numberField, {
                    onChange: () =>
                      setKycErrors((prev) => ({
                        ...prev,
                        [numberField]: "",
                        [uploadField]: "",
                      })),
                  })}
                  className="focus:border-primary dark:bg-dark-800 w-full rounded-l-lg rounded-r-none border border-gray-300 px-3 py-2 text-sm outline-none dark:border-gray-600"
                />
              </div>

              <label className="border-primary bg-primary/5 text-primary flex w-[32%] cursor-pointer items-center justify-center gap-1 rounded-l-none rounded-r-lg border border-l-0 border-dashed px-2 py-2 text-center text-xs">
                <PaperClipIcon className="size-4" />
                {value instanceof File ? "Change" : "Upload"}
                <input
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={(e) => {
                    onChange(e.target.files?.[0] || null);
                    setKycErrors((prev) => ({
                      ...prev,
                      [numberField]: "",
                      [uploadField]: "",
                    }));
                  }}
                />
              </label>
            </div>

            {value instanceof File && (
              <p className="mt-1 truncate text-xs text-green-600">
                {value.name}
              </p>
            )}

            {kycErrors[numberField] && (
              <p className="mt-1 text-xs text-red-600">
                {kycErrors[numberField]}
              </p>
            )}
            {kycErrors[uploadField] && (
              <p className="mt-1 text-xs text-red-600">
                {kycErrors[uploadField]}
              </p>
            )}
          </>
        )}
      />
    </div>
  );

  const handleFinalSubmit = async () => {
    const selected = selectedEmployee?.[0];
    if (!selected) {
      setSelectEmployeeError("Please select an employee to register.");
      setStep(1);
      return;
    }

   const valid = await trigger(STEP5_REQUIRED_FIELDS);
    if (!valid) return;

    setSubmitting(true);
    const values = getValues();

    const formData = buildFormData({
      employeeId: selected.id, // the actual row id from the "Select Employee" combobox
      financialYearId: values.financialYearId,
      firstName: values.firstName,
      lastName: values.lastName,
      middleName: values.middleName,
      dateOfBirth: values.dateOfBirth,
      gender: values.gender,
      maritalStatus: values.maritalStatus,
      bloodGroup: values.bloodGroup,
      personalMobileNo: values.personalMobileNo,
      personalEmail: values.personalEmail,

      aadharNumber: values.aadharNumber,
      aadharCardUpload: values.aadharCardUpload,
      drivingLicenceNumber: values.drivingLicenceNumber,
      drivingLicenceUpload: values.drivingLicenceUpload,
      panNumber: values.panNumber,
      panUpload: values.panUpload,
      voterIdNumber: values.voterIdNumber,
      voterIdUpload: values.voterIdUpload,

      address: values.address,
      country: values.country,
      state: values.state,
      city: values.city,
      pincode: values.pincode,

      sameAsPermanentAddress: values.sameAsPermanentAddress,
      permanentAddress: values.sameAsPermanentAddress
        ? values.address
        : values.permanentAddress,
      permanentCountry: values.sameAsPermanentAddress
        ? values.country
        : values.permanentCountry,
      permanentState: values.sameAsPermanentAddress
        ? values.state
        : values.permanentState,
      permanentCity: values.sameAsPermanentAddress
        ? values.city
        : values.permanentCity,
      permanentPincode: values.sameAsPermanentAddress
        ? values.pincode
        : values.permanentPincode,

      joiningDate: values.joiningDate,
      employeeType: values.employeeType,
      designation: values.designation,
      branchLocation: values.branchLocation,
      employeeStatus: values.employeeStatus,
      noticePeriod: values.noticePeriod,

      // ---- Work Information ----
      workingDays: values.workingDays.join(","),
      weeklyOff: values.weeklyOff,
      workingHoursFrom: values.workingHoursFrom,
      workingHoursTo: values.workingHoursTo,
      workingShift: values.workingShift,
    });

    try {
      const response = await Post("hr/employee/register", formData, true);
      if (response.data?.success) {
        toastsuccessmsg(
          response.data?.message || "Employee registered successfully.",
        );
        navigate("/employee/employeeRegister/employee-list");
      } else {
        toasterrormsg(response.data?.message || "Failed to register employee.");
      }
    } catch (error) {
      toasterrormsg("Something went wrong while saving the employee record.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Page title="Employee Register">
      <div className="transition-content mx-auto w-full px-(--margin-x) pb-8">
        <div className="flex items-center justify-between py-5 lg:py-6">
          <h2 className="dark:text-dark-50 border-primary text-primary border-b-4 text-xl font-bold tracking-wide lg:text-2xl">
            Employee Register
          </h2>
          <Link to="/employee/employeeRegister">
            <Button color="primary" variant="outlined">
              <ChevronLeftIcon className="size-6" />
              <span>Back</span>
            </Button>
          </Link>
        </div>

        <div className="mb-2 w-80 ">
          <Combobox
            data={employeeOptions}
            displayField="label"
            value={selectedEmployee[0] ?? null}
            onChange={(val: any) =>
              setSelectedEmployee(val ? (Array.isArray(val) ? val : [val]) : [])
            }
            placeholder="Select Employee"
            label="Select Employee"
            searchFields={["employeeName", "mobileNumber"]}
          />
          {selectEmployeeError && (
            <p className="mt-1 text-xs text-red-600">{selectEmployeeError}</p>
          )}
        </div>

        <Card className="mb-6 p-4 sm:p-6 lg:whitespace-nowrap">
          <Stepper
            steps={STEP_LABELS}
            currentStep={step}
            // onStepClick={(clickedStep) => setStep(clickedStep)}
          />
        </Card>

        {/* ---------------- STEP 1: PERSONAL DETAILS ---------------- */}
        {step === 1 && (
          <div className="space-y-6">
            <Card className="space-y-4 p-4 sm:p-6">
              <h3 className="dark:text-dark-50 border-primary text-primary border-b-4 w-37 text-lg font-bold tracking-wide lg:text-lg">
                Personal Details
              </h3>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Input
                  {...register("employeeId")}
                  label="Employee ID"
                  readOnly
                  disabled
                  placeholder="Generating..."
                  className="dark:bg-dark-700 bg-gray-100"
                />
                <Input
                  {...register("firstName", {
                    required: "First name is required",
                  })}
                  label="First Name"
                  placeholder="Enter first name"
                  error={errors.firstName?.message}
                />
                <Input
                  {...register("lastName", {
                    required: "Last name is required",
                  })}
                  label="Last Name"
                  placeholder="Enter last name"
                  error={errors.lastName?.message}
                />
                <Input
                  {...register("middleName")}
                  label="Middle Name"
                  placeholder="Enter middle name"
                />
                <Controller
                  control={control}
                  name="dateOfBirth"
                  rules={{ required: "Date of birth is required" }}
                  render={({ field: { value, onChange } }) => (
                    <DatePicker
                      label="Date of Birth"
                      placeholder="Choose date..."
                      value={value}
                      onChange={(_dates, dateStr) => onChange(dateStr)}
                      error={errors.dateOfBirth?.message}
                    />
                  )}
                />
                <Controller
                  control={control}
                  name="gender"
                  rules={{ required: "Gender is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={genderOptions}
                      value={
                        genderOptions.find((item) => item.id === value) || null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Gender"
                      placeholder="Select gender"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.gender?.message}
                    />
                  )}
                />
                <Controller
                  control={control}
                  name="maritalStatus"
                  rules={{ required: "Marital status is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={maritalStatusOptions}
                      value={
                        maritalStatusOptions.find(
                          (item) => item.id === value,
                        ) || null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Marital Status"
                      placeholder="Select marital status"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.maritalStatus?.message}
                    />
                  )}
                />
                <Controller
                  control={control}
                  name="bloodGroup"
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={bloodGroupOptions}
                      value={
                        bloodGroupOptions.find((item) => item.id === value) ||
                        null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Blood Group"
                      placeholder="Select blood group"
                      displayField="label"
                      searchFields={["label"]}
                    />
                  )}
                />
                <Input
                  {...register("personalMobileNo", {
                    required: "Personal mobile number is required",
                  })}
                  label="Personal Mobile No"
                  placeholder="Enter mobile number"
                  error={errors.personalMobileNo?.message}
                />
                <Input
                  {...register("personalEmail")}
                  label="Personal Email"
                  type="email"
                  placeholder="Enter personal email"
                />
              </div>
            </Card>

            <div className="flex justify-end gap-3 pt-2">
              <Button
                type="button"
                onClick={() => navigate("/employeemaster/employee-list")}
              >
                Cancel
              </Button>
              <Button
                type="button"
                color="primary"
                onClick={() => {
                  if (!selectedEmployee?.[0]) {
                    setSelectEmployeeError(
                      "Please select an employee to register.",
                    );
                    return;
                  }
                  goNext(STEP1_REQUIRED_FIELDS, 2);
                }}
              >
                Next: Identity & KYC
              </Button>
            </div>
          </div>
        )}

        {/* ---------------- STEP 2: IDENTITY & KYC ---------------- */}
        {step === 2 && (
          <div className="space-y-6">
            <Card className="space-y-4 p-4 sm:p-6">
              <h3 className="dark:text-dark-50 border-primary text-primary border-b-4 w-37 text-lg font-bold tracking-wide lg:text-lg">
                Identity & KYC
              </h3>

              <div className="grid gap-4 sm:grid-cols-2">
                {renderKycField(
                  "aadharNumber",
                  "aadharCardUpload",
                  "Aadhar Card",
                )}
                {renderKycField(
                  "drivingLicenceNumber",
                  "drivingLicenceUpload",
                  "Driving Licence",
                )}
                {renderKycField("panNumber", "panUpload", "PAN Card")}
                {renderKycField("voterIdNumber", "voterIdUpload", "Voter ID")}
              </div>
            </Card>

            <div className="flex justify-between gap-3 pt-2">
              <Button variant="outlined" onClick={() => setStep(1)}>
                <ChevronLeftIcon className="size-4" /> Back
              </Button>
              <Button
                type="button"
                color="primary"
                onClick={() => {
                  if (!validateKycStep()) return;
                  setStep(3);
                }}
              >
                Next: Address Details
              </Button>
            </div>
          </div>
        )}

        {/* ---------------- STEP 3: ADDRESS DETAILS ---------------- */}
        {step === 3 && (
          <div className="space-y-6">
            <Card className="space-y-4 p-4 sm:p-6">
             <h3 className="dark:text-dark-50 border-primary text-primary border-b-4 w-40 text-lg font-bold tracking-wide lg:text-lg">
                Current Address
              </h3>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Input
                  {...register("address", { required: "Address is required" })}
                  label="Address"
                  placeholder="Enter address"
                  className="sm:col-span-2 lg:col-span-1"
                  error={errors.address?.message}
                />
                <Controller
                  control={control}
                  name="country"
                  rules={{ required: "Country is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={countryOptions}
                      value={
                        countryOptions.find((item) => item.label === value) ||
                        null
                      }
                      onChange={(item: any) => {
                        onChange(item?.label ?? "");
                        setCurrentCountryCode(item?.id ?? "");
                        setValue("state", "");
                        setValue("city", "");
                        setCurrentStateCode("");
                      }}
                      label="Country"
                      placeholder="Select country"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.country?.message}
                    />
                  )}
                />
                <Controller
                  control={control}
                  name="state"
                  rules={{ required: "State is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={currentStateOptions}
                      value={
                        currentStateOptions.find(
                          (item) => item.label === value,
                        ) || null
                      }
                      onChange={(item: any) => {
                        onChange(item?.label ?? "");
                        setCurrentStateCode(item?.id ?? "");
                        setValue("city", "");
                      }}
                      label="State"
                      placeholder={
                        currentCountryCode
                          ? "Select state"
                          : "Select country first"
                      }
                      displayField="label"
                      searchFields={["label"]}
                      disabled={!currentCountryCode}
                      error={errors.state?.message}
                    />
                  )}
                />
                <Controller
                  control={control}
                  name="city"
                  rules={{ required: "District/City is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={currentCityOptions}
                      value={
                        currentCityOptions.find(
                          (item) => item.label === value,
                        ) || null
                      }
                      onChange={(item: any) => onChange(item?.label ?? "")}
                      label="District / City"
                      placeholder={
                        currentStateCode
                          ? "Select district/city"
                          : "Select state first"
                      }
                      displayField="label"
                      searchFields={["label"]}
                      disabled={!currentStateCode}
                      error={errors.city?.message}
                    />
                  )}
                />
                <Input
                  {...register("pincode", { required: "Pincode is required" })}
                  label="Pincode"
                  placeholder="Enter pincode"
                  error={errors.pincode?.message}
                />
              </div>
            </Card>

            <Card className="space-y-4 p-4 sm:p-6">
              <Controller
                control={control}
                name="sameAsPermanentAddress"
                render={({ field: { value, onChange } }) => (
                  <Switch
                    checked={value}
                    onChange={(e) => onChange(e.target.checked)}
                    label="Permanent address is same as current address"
                  />
                )}
              />

              {!sameAsPermanentAddress && (
                <div className="space-y-4 pt-2">
                  <h3 className="dark:text-dark-100 text-lg font-medium text-gray-800">
                    Permanent Address
                  </h3>
                  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    <Input
                      {...register("permanentAddress")}
                      label="Address"
                      placeholder="Enter permanent address"
                      className="sm:col-span-2 lg:col-span-1"
                    />
                    <Controller
                      control={control}
                      name="permanentCountry"
                      render={({ field: { value, onChange } }) => (
                        <Combobox
                          data={countryOptions}
                          value={
                            countryOptions.find(
                              (item) => item.label === value,
                            ) || null
                          }
                          onChange={(item: any) => {
                            onChange(item?.label ?? "");
                            setPermanentCountryCode(item?.id ?? "");
                            setValue("permanentState", "");
                            setValue("permanentCity", "");
                            setPermanentStateCode("");
                          }}
                          label="Country"
                          placeholder="Select country"
                          displayField="label"
                          searchFields={["label"]}
                        />
                      )}
                    />
                    <Controller
                      control={control}
                      name="permanentState"
                      render={({ field: { value, onChange } }) => (
                        <Combobox
                          data={permanentStateOptions}
                          value={
                            permanentStateOptions.find(
                              (item) => item.label === value,
                            ) || null
                          }
                          onChange={(item: any) => {
                            onChange(item?.label ?? "");
                            setPermanentStateCode(item?.id ?? "");
                            setValue("permanentCity", "");
                          }}
                          label="State"
                          placeholder={
                            permanentCountryCode
                              ? "Select state"
                              : "Select country first"
                          }
                          displayField="label"
                          searchFields={["label"]}
                          disabled={!permanentCountryCode}
                        />
                      )}
                    />
                    <Controller
                      control={control}
                      name="permanentCity"
                      render={({ field: { value, onChange } }) => (
                        <Combobox
                          data={permanentCityOptions}
                          value={
                            permanentCityOptions.find(
                              (item) => item.label === value,
                            ) || null
                          }
                          onChange={(item: any) => onChange(item?.label ?? "")}
                          label="District / City"
                          placeholder={
                            permanentStateCode
                              ? "Select district/city"
                              : "Select state first"
                          }
                          displayField="label"
                          searchFields={["label"]}
                          disabled={!permanentStateCode}
                        />
                      )}
                    />
                    <Input
                      {...register("permanentPincode")}
                      label="Pincode"
                      placeholder="Enter pincode"
                    />
                  </div>
                </div>
              )}
            </Card>

            <div className="flex justify-between gap-3 pt-2">
              <Button variant="outlined" onClick={() => setStep(2)}>
                <ChevronLeftIcon className="size-4" /> Back
              </Button>
              <Button
                type="button"
                color="primary"
                onClick={() => goNext(STEP3_REQUIRED_FIELDS, 4)}
              >
                Next: Employee Details
              </Button>
            </div>
          </div>
        )}

        {/* ---------------- STEP 4: EMPLOYEE DETAILS ---------------- */}
        {step === 4 && (
          <div className="space-y-6">
            <Card className="space-y-4 p-4 sm:p-6">
              <h3 className="dark:text-dark-50 border-primary text-primary border-b-4 w-40 text-lg font-bold tracking-wide lg:text-lg">
                Employee Details
              </h3>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <Controller
                  control={control}
                  name="joiningDate"
                  rules={{ required: "Joining date is required" }}
                  render={({ field: { value, onChange } }) => (
                    <DatePicker
                      label="Joining Date"
                      placeholder="Choose date..."
                      value={value}
                      onChange={(_dates, dateStr) => onChange(dateStr)}
                      error={errors.joiningDate?.message}
                    />
                  )}
                />
                <Controller
                  control={control}
                  name="employeeType"
                  rules={{ required: "Employee type is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={employeeTypeOptions}
                      value={
                        employeeTypeOptions.find((item) => item.id === value) ||
                        null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Employee Type"
                      placeholder="Select employee type"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.employeeType?.message}
                    />
                  )}
                />
                <Input
                  {...register("designation", {
                    required: "Designation is required",
                  })}
                  label="Designation"
                  placeholder="Enter designation"
                  error={errors.designation?.message}
                />
                <Input
                  {...register("branchLocation")}
                  label="Branch Location"
                  placeholder="Enter branch location"
                />
                <Controller
                  control={control}
                  name="employeeStatus"
                  rules={{ required: "Employee status is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={employeeStatusOptions}
                      value={
                        employeeStatusOptions.find(
                          (item) => item.id === value,
                        ) || null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Employee Status"
                      placeholder="Select employee status"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.employeeStatus?.message}
                    />
                  )}
                />
                <Input
                  {...register("noticePeriod")}
                  label="Notice Period"
                  placeholder="e.g. 30 days"
                />
              </div>
            </Card>

            <div className="flex justify-between gap-3 pt-2">
              <Button variant="outlined" onClick={() => setStep(3)}>
                <ChevronLeftIcon className="size-4" /> Back
              </Button>
              <Button
                type="button"
                color="primary"
                onClick={() => goNext(STEP4_REQUIRED_FIELDS, 5)}
              >
                Next: Work Information
              </Button>
            </div>
          </div>
        )}

        {/* ---------------- STEP 5: WORK INFORMATION ---------------- */}
        {step === 5 && (
          <div className="space-y-6">
            <Card className="space-y-6 p-4 sm:p-6">
            <h3 className="dark:text-dark-50 border-primary text-primary border-b-4 w-40 text-lg font-bold tracking-wide lg:text-lg">
                Work Information
              </h3>

              {/* Working Days — multi-select toggle pills */}
              <Controller
                control={control}
                name="workingDays"
                rules={{
                  validate: (value) =>
                    (value && value.length > 0) ||
                    "Select at least one working day",
                }}
                render={({ field: { value, onChange } }) => (
                  <div>
                    <label className="mb-4 block text-sm font-medium text-gray-700 dark:text-gray-200">
                      Working Days
                    </label>
                    <div className="flex flex-wrap gap-2">
                      {daysOfWeekOptions.map((day) => {
                        const checked = value?.includes(day.id);
                        return (
                          <button
                            key={day.id}
                            type="button"
                            onClick={() => {
                              if (checked) {
                                onChange(
                                  value.filter((d) => d !== day.id),
                                );
                              } else {
                                onChange([...(value || []), day.id]);
                              }
                            }}
                            className={
                              checked
                                ? "bg-primary border-primary rounded-full border px-3 py-1.5 text-xs font-medium text-white"
                                : "dark:border-gray-600 dark:text-gray-200 rounded-full border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700"
                            }
                          >
                            {day.label}
                          </button>
                        );
                      })}
                    </div>
                    {errors.workingDays && (
                      <p className="mt-1 text-xs text-red-600">
                        {errors.workingDays.message as string}
                      </p>
                    )}
                  </div>
                )}
              />

              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {/* Weekly Off */}
                <Controller
                  control={control}
                  name="weeklyOff"
                  rules={{ required: "Weekly off is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={daysOfWeekOptions}
                      value={
                        daysOfWeekOptions.find((item) => item.id === value) ||
                        null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Weekly Off"
                      placeholder="Select weekly off"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.weeklyOff?.message}
                    />
                  )}
                />

                {/* Working Hours From */}
                <Controller
                  control={control}
                  name="workingHoursFrom"
                  rules={{ required: "Working hours (from) is required" }}
                  render={({ field: { value, onChange } }) => (
                    <DatePicker
                      label="Working Hours From"
                      placeholder="Choose time..."
                      value={value}
                      onChange={(_dates, timeStr) => onChange(timeStr)}
                      options={{
                        enableTime: true,
                        noCalendar: true,
                        dateFormat: "H:i",
                        time_24hr: true,
                      }}
                      error={errors.workingHoursFrom?.message}
                    />
                  )}
                />

                {/* Working Hours To */}
                <Controller
                  control={control}
                  name="workingHoursTo"
                  rules={{ required: "Working hours (to) is required" }}
                  render={({ field: { value, onChange } }) => (
                    <DatePicker
                      label="Working Hours To"
                      placeholder="Choose time..."
                      value={value}
                      onChange={(_dates, timeStr) => onChange(timeStr)}
                      options={{
                        enableTime: true,
                        noCalendar: true,
                        dateFormat: "H:i",
                        time_24hr: true,
                      }}
                      error={errors.workingHoursTo?.message}
                    />
                  )}
                />

                {/* Working Shift */}
                <Controller
                  control={control}
                  name="workingShift"
                  rules={{ required: "Working shift is required" }}
                  render={({ field: { value, onChange } }) => (
                    <Combobox
                      data={workingShiftOptions}
                      value={
                        workingShiftOptions.find(
                          (item) => item.id === value,
                        ) || null
                      }
                      onChange={(item: any) => onChange(item?.id ?? "")}
                      label="Working Shift"
                      placeholder="Select working shift"
                      displayField="label"
                      searchFields={["label"]}
                      error={errors.workingShift?.message}
                    />
                  )}
                />
              </div>
            </Card>

            <div className="flex justify-between gap-3 pt-2">
              <Button
                variant="outlined"
                disabled={submitting}
                onClick={() => setStep(4)}
              >
                <ChevronLeftIcon className="size-4" /> Back
              </Button>
              <Button
                type="button"
                color="primary"
                disabled={submitting}
                onClick={handleFinalSubmit}
              >
                {submitting ? "Saving..." : "Submit"}
              </Button>
            </div>
          </div>
        )}
      </div>
    </Page>
  );
}